/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClientCard: typeof import('./src/client/components/ClientCard.vue')['default']
    ClientTokens: typeof import('./src/client/components/ClientTokens.vue')['default']
    DataTable: typeof import('./src/client/components/DataTable.vue')['default']
    DateTimePicker: typeof import('./src/client/components/DateTimePicker.vue')['default']
    HelloWorld: typeof import('./src/client/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/client/components/Loading.vue')['default']
    LogoAnimation: typeof import('./src/client/components/LogoAnimation.vue')['default']
    NoItems: typeof import('./src/client/components/NoItems.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WhatsappClients: typeof import('./src/client/components/WhatsappClients.vue')['default']
  }
}
